---

  - name: "update packages"
    become: true
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: true
    apt:
      upgrade: yes

  - name: "install nodejs"
    become: true
    apt:
      update_cache: yes
      name: nodejs
      state: present

  - name: "install npm"
    become: true
    apt:
      update_cache: yes
      name: npm
      state: present