---

  - name: "update packages"
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: true
    apt:
      autoremove: yes

  - name: "install nodejs"
    become: yes
    apt:
      update_cache: yes
      name: ["nodejs", "npm"]
      state: latest

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present