version: 2.1

jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              pwd
              ls -la


workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      - create_infrastructure
      